networks:
  mongo-cluster:
    driver: bridge

services:
  mongo1:
    image: mongo:latest
    hostname: mongo1
    container_name: mongo1
    ports: 
      - 27017:27017
    networks:
      - mongo-cluster
    command: mongod --replSet rs0 --bind_ip localhost,mongo1
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:latest
    hostname: mongo2
    container_name: mongo2
    ports: 
      - 27018:27017
    networks:
      - mongo-cluster
    command: mongod --replSet rs0 --bind_ip localhost,mongo2
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:latest
    hostname: mongo3
    container_name: mongo3
    ports: 
      - 27019:27017
    networks:
      - mongo-cluster
    command: mongod --replSet rs0 --bind_ip localhost,mongo3
    volumes:
      - mongo3_data:/data/db

  mongo-express:
    image: mongo-express:latest
    networks:
      - mongo-cluster
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo1
      - ME_CONFIG_MONGODB_PORT=27017
    hostname: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo1

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
