networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

volumes:
  redis1_data:
  redis2_data:
  redis3_data:
  redis4_data:
  redis5_data:

services:
  redis1:
    image: redis:latest
    hostname: redis1
    container_name: redis1
    ports:
      - 27017:6379
    networks:
      - redis-cluster
    volumes:
      - redis1_data:/data/db
      - ./redis-cluster.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  redis2:
    image: redis:latest
    hostname: redis2
    container_name: redis2
    ports:
      - 27018:6379
    networks:
      - redis-cluster
    volumes:
      - redis2_data:/data/db
    command: redis-server --slaveof 172.18.0.2 6379
    depends_on:
      - redis1

  redis3:
    image: redis:latest
    hostname: redis3
    container_name: redis3
    ports:
      - 27019:6379
    networks:
      - redis-cluster
    volumes:
      - redis3_data:/data/db
    command: redis-server --slaveof 172.18.0.2 6379
    depends_on:
      - redis1

  redis4:
    image: redis:latest
    hostname: redis4
    container_name: redis4
    ports:
      - 27020:6379
    networks:
      - redis-cluster
    volumes:
      - redis4_data:/data/db
    command: redis-server --slaveof 172.18.0.2 6379
    depends_on:
      - redis1

  redis5:
    image: redis:latest
    hostname: redis5
    container_name: redis5
    ports:
      - 27021:6379
    networks:
      - redis-cluster
    volumes:
      - redis5_data:/data/db
    command: redis-server --slaveof 172.18.0.2 6379
    depends_on:
      - redis1
