networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

volumes:
  redis1_data:
  redis2_data:
  redis3_data:

services:
  redis1:
    image: redis:latest
    hostname: redis1
    container_name: redis1
    ports:
      - 27017:27017
    networks:
      - redis-cluster
    volumes:
      - redis1_data:/data/db
      - ./redis-cluster.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  redis2:
    image: redis:latest
    hostname: redis2
    container_name: redis2
    ports:
      - 27018:27018
    networks:
      - redis-cluster
    volumes:
      - redis2_data:/data/db
    command: redis-server --slaveof 172.18.0.2 7000
    depends_on:
      - redis1

  redis3:
    image: redis:latest
    hostname: redis3
    container_name: redis3
    ports:
      - 27019:27019
    networks:
      - redis-cluster
    volumes:
      - redis3_data:/data/db
    command: redis-server --slaveof 172.18.0.2 7000
    depends_on:
      - redis1
